default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: grimace_development

stress:
  <<: *default
  database: grimace_stress

test:
  <<: *default
  database: grimace_test